### PR TITLE
test: fix old tests, add react scripts

### LINKED ISSUE #212: bug: clean install of project does not work
# Bug report

## Describe the bug

npm throws a resolution error when doing a fresh install (deleting package-lock.json and running `npm install`)

## To Reproduce

1. Clone repo
2. Delete package-lock.json
3. run `npm install`

## Expected behavior

Proper package-lock.json to be generated without errors

## Screenshots

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: @supabase/ui@0.1.3
npm ERR! Found: postcss@7.0.35
npm ERR! node_modules/postcss
npm ERR!   dev postcss@"^7.0.35" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer postcss@"^8.1.0" from postcss-modules-values@4.0.0
npm ERR! node_modules/postcss-modules-values
npm ERR!   dev postcss-modules-values@"^4.0.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

## System information

- OS: Windows
- Version of Node.js: v15.12.0

## Additional context

When trying to resolve deps, 
Got more resolution errors.

### PR DESCRIPTION
**Pull request by YashKandalkar**
### Brief:
- Updated all of the old tests which had old class names.
- Added react-scripts as dev dependency to run tests.
### Dependencies:
- I had to upgrade `typescript` to `4.2.2` because of [an error when running storybook](https://github.com/styleguidist/react-docgen-typescript/issues/356#issuecomment-849406193)
- Had to also add `"webpack": "^4.44.2"` because react-scripts was having resolution errors. We can also add a .env with `SKIP_PREFLIGHT_CHECK=true` to suppress the error. (Also have to manually install `babel-loader@8.1.0` because `babel-loader@8.2.2` also throws the same error when running `npm test`) 

### Other changes:
- The changes in `tsconfig.json` were automatically added by react-scripts when running tests.
- endOfLine in .prettierrc was added because vscode was giving error on every line ending because of files from different environments with diff. line endings
- In package.json, jest was added because one of the tests has imports from react-feathers which was throwing syntax error, import is not defined. So that module needed to be transformed during testing too.

### Tests:
- Had to add TYPES and SIZES in Button.test.js as they are no longer exported.
- Also added `...props` in some components and passed them as a prop to the rendered elements because `data-testid` was not being added as a prop to elements and tests were failing.
- `strokeWidth` was not passed as a prop to the svg element in Icon.tsx, did that too. (and added {...props} to the svg)

## What is the current behavior?

Maybe we can close #212 also, because clean install does work, but **only** with `--legacy-peer-deps`. Maybe we can add this in the readme somewhere for contributors? (And also to install `webpack@4.44.2` and `babel-loader@8.1.0` for running tests, if we do not plan on adding SKIP_PREFLIGHT_CHECK=true in .env

## What is the new behavior?

- Tested storybook, `npm run storybook` works properly.
- All tests also pass
image

### CODE REVIEW

**Comment by YashKandalkar** [comment]
Tell me if I have to add `lf` in [here](https://github.com/supabase/ui/pull/214/commits/8911185c95e4f2800aa409c5257c12d37cf6355b#diff-663ade211b3a1552162de21c4031fcd16be99407aae5ceecbb491a2efc43d5d2R5), or if there are any changes required anywhere else

**Comment by MildTomato** [comment]
Nice @YashKandalkar 🔥  finally we have some tests! 

it's quite late here, i'll have to check this out tomorrow

**Comment by MildTomato** [comment]
@YashKandalkar There's a build error in the Button component if you run `npm run build` locally.
Could you take a look?

```
[!] (plugin rpt2) Error: /Users/jonathansummers-muir/Sites/Supabase/ui/src/components/Button/Button.tsx(77,11): semantic error TS2322: Type 'undefined' is not assignable to type '() => HTMLElement'.
src/components/Button/Button.tsx
```

**Comment by YashKandalkar** [comment]
@MildTomato There were some typing issues in some files already in the code but now these errors are thrown due to the `strict: true` in tscofig.json.

I fixed all of them, but these are some questions I had:
- `layout` prop in FormLayout.tsx was not optional. But we have checks in our code (`layout && ...`), so I made it optional. Tell me if this was intentional.
- The `align` prop in FormLayout is optional, but we are only checking for 'left' and 'right' and adding `flex-left` and `flex-right` there accordingly. But when it is undefined, no class is added to it. Is this also intentional?
- I couldn't understand [this](https://github.com/supabase/ui/blob/develop/src/components/Toggle/Toggle.tsx#L67) line. 
  was it supposed to be `align={layout === 'vertical' ? align : undefined}`? Because align is `string | undefined` but we were passing a boolean here.

### Some changes I had to make: 
- Accordion.tsx:
  - Had to remove Required<> from ContextValue as we are setting onChange as undefined at start.
- autoComplete prop in some files (like Input.tsx) had values other than `'on' | 'off' | undefined`, had to change that [(MDN)](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea#attr-autocomplete)
- And some other changes which shouldn't change the logic of components (other than the ones I've mentioned at the top)

The build works now, there's just a circular imports warning

**Comment by MildTomato** [comment]
@YashKandalkar alright i'll check back shortly and review.
sorry takes a bit longer this one than the other PRs

**Comment by YashKandalkar** [comment]
@MildTomato No problem!

File: src/components/ContextMenu/ContextMenu.tsx [hunk 1]
```diff
@@ -67,7 +67,7 @@ export function Item({ children, icon, disabled, onClick }: ItemProps) {
     <RadixContextMenu.Item
       className={ContextMenuStyles['sbui-contextmenu-item']}
       disabled={disabled}
-      onSelect={onClick ? onClick : null}
+      onSelect={onClick ? onClick : undefined}
```
Comment (jonthomp) [inline src/components/ContextMenu/ContextMenu.tsx:70]: This could just be
```suggestion
      onSelect={onClick}
```

**Comment by MildTomato** [comment]
thanks @jonthomp for reviewing

File: src/components/ContextMenu/ContextMenu.tsx (hunk 1 above)
Comment (YashKandalkar) [reply src/components/ContextMenu/ContextMenu.tsx:70]: Correct! Resolving.

File: src/components/Input/Input.tsx [hunk 2]
```diff
@@ -250,7 +250,7 @@ function TextArea({
       size={size}
     >
       <textarea
-        autoComplete={autoComplete && 'autoComplete'}
```
Comment (YashKandalkar) [inline src/components/Input/Input.tsx:253]: @jonthomp here, typescript throws an error saying autoComplete has type `string | undefined`, but we are passing a boolean here. The TextAreaProps interface has autoComplete typed as boolean, but since the autoComplete on textarea says it's string, we can make the type of autoComplete in the interface as string too.
If it has to stay boolean, then we will have to do something like 
`autoComplete={autoComplete ? 'on' : 'off'}` this here. Which one should I do?

File: src/components/Auth/Auth.tsx [hunk 3]
```diff
@@ -281,7 +281,7 @@ function EmailAuth({
         <Space size={3} direction={'vertical'}>
           <Input
             label="Email address"
-            autoComplete="email"
+            autoComplete="on"
```
[the remark this answers is not in the document]
Comment (YashKandalkar) [reply src/components/Auth/Auth.tsx:284]: Got it. Will revert these changes

File: src/components/Input/Input.tsx (hunk 2 above)
Comment (jonthomp) [reply src/components/Input/Input.tsx:253]: Hey @YashKandalkar sorry I got halfway through a review and then the fastly outage happened!

I think for `textarea`  `autoComplete={autoComplete ? 'on' : 'off'}` is the right way to go and will keep the interface backwards compatible too

File: src/lib/Layout/FormLayout/FormLayout.tsx [hunk 4]
```diff
@@ -13,7 +13,7 @@ type Props = {
   id?: string
   label?: string
   labelOptional?: string
-  layout: 'horizontal' | 'vertical'
+  layout?: 'horizontal' | 'vertical'
```
Comment (jonthomp) [inline src/lib/Layout/FormLayout/FormLayout.tsx:16]: I think should `layout` should have a default value if it's being made optional so that we keep the expected behaviour that it is always one or the other

File: src/components/Accordion/Accordion.tsx [hunk 5]
```diff
@@ -80,7 +80,12 @@ export function Item({ children, className, label, id }: ItemProps) {
     buttonClasses.push(className)
   }
 
-  const isDefaultActive = defaultActiveId.includes(id)
+  let isDefaultActive
```
Comment (jonthomp) [inline src/components/Accordion/Accordion.tsx:83]: This could be `const isDefaultActive = id ? defaultActiveId?.includes(id) : false`

File: src/components/Input/Input.tsx (hunk 2 above)
Comment (YashKandalkar) [reply src/components/Input/Input.tsx:253]: Hey, no problem!

Okay I will do that then.

File: src/lib/Layout/FormLayout/FormLayout.tsx (hunk 4 above)
Comment (YashKandalkar) [reply src/lib/Layout/FormLayout/FormLayout.tsx:16]: Okay, makes sense.

Comment (YashKandalkar) [reply src/lib/Layout/FormLayout/FormLayout.tsx:16]: I will just keep it as required for now since it was required before, there's not really any need to change it, maybe we can have a default vertical later

Comment (YashKandalkar) [reply src/lib/Layout/FormLayout/FormLayout.tsx:16]: Actually, after changing this I just saw the errors in `Input.tsx`. In input.tsx, the components have the `layout` prop which is optional (Input and TextArea both), and both these components use the FormLayout component. Now, we either need to give a default layout in these 2 components or change the `layout` in FormLayout to be optional and give a default there.

Comment (MildTomato) [reply src/lib/Layout/FormLayout/FormLayout.tsx:16]: Oh yea, this might be confusing. 

We have a layout prop on data input components (Input, Select, Radio etc) so a user of the library can pass a preferred layout option `"horizontal"` or `"vertical"`.

the components always have a default (i think..) hence this wasn't optional in the FormLayout, to make sure that they always had layout prop set. I think it's usually horizontal - I guess if they're all horizontal then really FormLayout should have a default of horizontal, and the rest of the components don't need to set a default value.

File: src/components/Toggle/Toggle.tsx [hunk 6]
```diff
@@ -64,7 +66,7 @@ function Toggle({
       layout={layout}
       id={id}
       error={error}
-      align={layout === 'vertical' && align}
+      align={layout === 'vertical' ? align : undefined}
```
Comment (MildTomato) [inline src/components/Toggle/Toggle.tsx:69]: this might break the layout for Toggle - i can have a look and check.

File: src/lib/Layout/FormLayout/FormLayout.tsx (hunk 4 above)
Comment (MildTomato) [reply src/lib/Layout/FormLayout/FormLayout.tsx:16]: I'd probably opt for the FormLayout having a default, just to make it simpler. 

Although I think Toggle is the odd one out, because it uses `align` and it has a "vertical" 'layout`. So just check the components are looking ok with whatever changes you put in ;-)

File: src/components/Toggle/Toggle.tsx (hunk 6 above)
Comment (YashKandalkar) [reply src/components/Toggle/Toggle.tsx:69]: `layout === 'vertical' && align` actually returns `false` when `layout` is not `vertical`, so typescript throws an error because type of `align` in FormLayout is `string | undefined`. 
`layout === 'vertical' ? align : undefined` This returns undefined if `layout` isn't `vertical`.

I also tested the alignment in storybook and the left right and undefined works fine when layout is vertical. (and do nothing when layout is horizontal or undefined)

Nothing really changes as align was only being set as `'left'` `'right'` when layout was vertical and this is doing the same thing except it sets align as undefined when `layout` is not `'vertical'`, while earlier it was being set to false

File: src/lib/Layout/FormLayout/FormLayout.tsx (hunk 4 above)
Comment (YashKandalkar) [reply src/lib/Layout/FormLayout/FormLayout.tsx:16]: Alrighty, `layout` optional in FormLayout with a default `'horizontal'` works with all components I think (checked in storybook), including Toggle

File: src/components/Toggle/Toggle.tsx [hunk 7]
```diff
@@ -45,7 +45,7 @@ function Toggle({
 
   function onClick(e: React.MouseEvent<HTMLButtonElement>) {
     // '`onChange` callback for this component
-    if (onChange) onChange(active)
+    if (onChange) onChange(!active)
```
Comment (YashKandalkar) [inline src/components/Toggle/Toggle.tsx:52]: onChange was given false when Toggle was pressed and true when it was not, it should be `!active`

Comment (MildTomato) [reply src/components/Toggle/Toggle.tsx:52]: ah yea, this looks better.

**Comment by MildTomato** [comment]
sorry @YashKandalkar, just looking at this now

**Comment by MildTomato** [comment]
>Had to also add "webpack": "^4.44.2" because react-scripts was having resolution errors. We can also add a .env with SKIP_PREFLIGHT_CHECK=true to suppress the error. (Also have to manually install babel-loader@8.1.0 because babel-loader@8.2.2 also throws the same error when running npm test)

I don't get this error - @YashKandalkar could you do a fresh npm install and see if you still get an error.
I've removed webpack from package.json https://github.com/supabase/ui/pull/214/commits/4da517e2e18e5e43fd8b2ef2b3b93d7337eb54ff

**Comment by YashKandalkar** [comment]
@MildTomato That error comes when running `npm test`, react-script needs these 2 packages (babel-loader@8.1.0 and webpack@4.44.2).
I just did a fresh install but these 2 packages are required for running npm test.
 This is the error if you want to see:
image

It says to not install it manually but it doesn't work otherwise.

Adding a .env file with `SKIP_PREFLIGHT_CHECK=true` suppresses this check, we don't need to install the 2 packages but `.env` is not ignored in .gitignore, .env.local is but react-script doesn't seem to read env vars from `.env.local`. 
Or else, we can add (`cross-env` ) and set this in the npm "test" script in package.json itself. 
Adding cross env is also a good idea since we have build and build watch command which sets the NODE_ENV env var which doesn't work on windows.

**Comment by MildTomato** [comment]
Yep, I ran `npm test` with a fresh install, without webpack installed and it seemed to work.
I'll have a look again.

**Comment by YashKandalkar** [comment]
Oh then it's possible that this is problem on my local environment.
It doesn't really affect the build and people who get this error while running tests can have a .env in the root with `SKIP_PREFLIGHT_CHECK=true` in it, and not push this .env in their PR.

**Comment by MildTomato** [comment]
What version of node and npm are you running?
I'll see if I can recreate this - be good to know what's causing this

**Comment by YashKandalkar** [comment]
Node: v15.12.0
Npm: 7.15.1

**Comment by i-pip** [comment]
> Node: v15.12.0
> Npm: 7.15.1

It appears the Node version is the issue here. I was getting all sorts of dependency resolution errors while using Node v14.17.0   but as soon as I switched to using Node v12 I could run `npm install` and `npm run storybook` and it ran ok... 

Looks like Node v14 upwards is more strict with dependency resolutions errors because they're treated as just warnings in v12. 

I'm using [fnm as node version manager](https://github.com/Schniz/fnm/) by the way (used nvm before but fnm is much faster and less resource intensive)

**Comment by MildTomato** [comment]
If anyone is interested, I've had no errors and i've currently got the following
node v15.12.0
npm 7.17.0

**Comment by YashKandalkar** [comment]
Oh try upgrading npm and see if I get the error again

**Comment by MildTomato** [comment]
@YashKandalkar any luck?

**Comment by YashKandalkar** [comment]
@MildTomato Nope, it doesn't work on my machine, tried latest node and npm versions.
`npm ls babel-loader` outputs this:
image

So storybook requires babel-loader@8.2.2 but react-script babel-loader@8.1.0

and for webpack:
SB requires webpack@4.46.0
But react-scripts: webpack@4.44.2
So, I wasn't able to fix this on my machine

**Comment by YashKandalkar** [comment]
@MildTomato I just opened this branch (YashKandalkar:test/fix-old-tests-add-react-scripts) in a docker container with node 16 and it worked perfectly, `npm install` (full clean install) and then `npm test`, both the commands worked perfectly fine!
So the earlier errors probably were problems on my local environment only.

**Comment by MildTomato** [comment]
@YashKandalkar awesome work - thanks for checking that with docker as well 😄 
OK, we can probably look at merging these tests in then, but without webpack for now.

**Review by MildTomato — APPROVED** [review]

**Comment by MildTomato** [comment]
Lets look at this as a good start for implementing testing, but anyone can feel free to add on to tests/improve/suggest other alternatives
