### PR TITLE
fix: [#256] a11y issue with links in Auth

### LINKED ISSUE #256: [Auth] Typography.Link isn't keyboard-accessible due to missing href
# Bug report

## Describe the bug

When navigating the forms in `Auth` with a keyboard, all anchor tags generated from `Typography.Link` aren't accessible, as the `href` attributed is not applied in the rendered element:

Screen Shot 2021-08-03 at 2 00 54 PM

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Run any of the examples utilizing `Auth` component from `@supabase/ui` or the example code from `README`
2. Navigate through the form fields with a `Tab` key
3. Observe how all links are skipped over and can't be focused on when using a keyboard

## Expected behavior

Links should be focusable and accessible when using a keyboard.

This currently happens due to the `href` attribute not being applied, as the `Typography.Link` component in `Auth` only uses  `onClick`.

Adding `tabindex="0"` to the anchor links will enable keyboard focusing, while retaining the rest of the functionality. Though, I would argue that to maintain semantical correctness use cases like these should be handled by a `button` styled like a link.

## Screenshots

**Current behaviour:**

https://user-images.githubusercontent.com/5657181/128063212-ef0f9f37-ee2d-4496-b5d9-90444412197e.mov

**Expected behaviour:**

(with `tabindex="0"` added manually for demo purposes)

https://user-images.githubusercontent.com/5657181/128063256-70f0cb27-a185-48cb-b9a4-3435862d0648.mov

## System information

- OS: macOS Catalina (`10.15.7`)
- Browser: Chrome `92.0.4515.107`
- Version of supabase-js: `0.32.0`
- Version of Node.js: `15.10.0`

## Additional context

I'd be happy to submit a PR for this if there are no concerns with the proposed solution? Thank you

### PR DESCRIPTION
**Pull request by mryechkin**
## What kind of change does this PR introduce?

Fixing an issue with keyboard accessibility of anchor links in `Auth` component. Updating `Auth` to have `Typography.Link` utilize `href` attribute, and add `id`'s to the various auth forms for semantical correctness.

- ~~Added `keyDownHandler()` in the `Link` component in order to enable activating with a keyboard (using `Space` or `Enter` - same as default `button` behaviour)~~ EDIT: This was reverted
- Updated `EmailAuth` to take in a new `id` prop (which is then assigned as `id` attribute on the `form`)
- Updated all auth views to specify an `id` attribute on forms
- Updated all `Typography.Link`'s in `Auth` to provide an `href` attribute, referencing the appropriate `id` from above (ie. `#auth-forgot-password`, `#auth-magic-link`, etc.)

Closes #256

## What is the current behavior?

When navigating with a keyboard using TAB key, links are skipped over. As a result, users aren't able to activate them with a keyboard, thus limiting full functionality of the component when assistive technologies are used.

https://user-images.githubusercontent.com/5657181/129482025-78eed938-3ebb-4b7b-9f00-3f2cbde87f72.mov

## What is the new behavior?

Navigating with a keyboard now gives proper focus, as well as enables `Space` and `Enter` key presses to activate the links

https://user-images.githubusercontent.com/5657181/129482261-1485febe-fe7d-4fb8-ae7f-09c78dcef0fb.mov

## Additional context

As discussed in #256

### CODE REVIEW

File: src/components/Typography/Link.tsx [hunk 1]
```diff
@@ -28,14 +28,26 @@ function Link({
     classes.push(className)
   }
 
+  function keyDownHandler(e: React.KeyboardEvent<HTMLAnchorElement>) {
```
Comment (MildTomato) [inline src/components/Typography/Link.tsx:31]: I think we are mis-using `<a>` tags here - can we take this out of this PR for now?

**Review by MildTomato — CHANGES_REQUESTED** [review]
looks good, but I think we need to remove the `<a>` tag behaviour changes

File: src/components/Typography/Link.tsx (hunk 1 above)
Comment (mryechkin) [reply src/components/Typography/Link.tsx]: @MildTomato done! Thanks for reviewing this 🙏

File: src/components/Typography/Link.tsx [hunk 2]
```diff
@@ -36,6 +36,7 @@ function Link({
       target={target}
       rel="noopener noreferrer"
       style={style}
+      tabIndex={0}
```
Comment (MildTomato) [inline src/components/Typography/Link.tsx:39]: sorry, can you also remove this

**Review by MildTomato — CHANGES_REQUESTED** [review]

File: src/components/Typography/Link.tsx (hunk 1 above)
Comment (MildTomato) [reply src/components/Typography/Link.tsx]: 👍 🚀

File: src/components/Typography/Link.tsx (hunk 2 above)
Comment (mryechkin) [reply src/components/Typography/Link.tsx]: Yes, sorry - I had thought it was still needed for focusing, but not the case. Removed

**Review by MildTomato — APPROVED** [review]
